#include "gba_video.h"
#include "gba_input.h"
#include "gba_interrupt.h"
#include "pcx.h"
#include "fade.h"

#include <stdlib.h>

//---------------------------------------------------------------------------------
// header for binary data generated by bin2o macro in makefile
//---------------------------------------------------------------------------------
#include "../build/tileset_img_raw.h"
#include "../build/tileset_pal_raw.h"

//---------------------------------------------------------------------------------
// storage space for palette data
//---------------------------------------------------------------------------------
u16 PaletteBuffer[256];

unsigned int frame;

//---------------------------------------------------------------------------------
void VblankInterrupt()
//---------------------------------------------------------------------------------
{
	frame += 1;
	ScanKeys();
}

void set_palette(const void* pal)
{
  u16 i;
  for(i = 0; i < 256; ++i)
    BG_COLORS[i] = ((u16*)pal)[i];
}


void set_tileset(u8 num, const void* img)
{
  u16 i;
  for(i = 0; i < 1024; ++i)
    {
      u8 x, y;
      for(y = 0; y < 8; ++y)
        for(x = 0; x < 4; ++x)
          ((u16*)CHAR_BASE_ADR(num))[(i * (8*4) + y*4 + x)] =
            ((u16*)img)[(y + ((i*4)/128)*8) * 128 + x + ((i*4)%128)];
    }
}

int main(void)
{
  // Set up the interrupt handlers
  InitInterrupt();

  SetInterrupt( Int_Vblank, VblankInterrupt);

  // Enable Vblank Interrupt to allow VblankIntrWait
  EnableInterrupt(Int_Vblank);

  // Allow Interrupts
  REG_IME = 1;

  SetMode( MODE_0 | BG0_ON | BG1_ON );		// screen mode & background to display

  BGCTRL[0] = BG_PRIORITY(0) | CHAR_BASE(2) | BG_MOSAIC | BG_256_COLOR | SCREEN_BASE(0) | BG_SIZE_0;
  BGCTRL[1] = BG_PRIORITY(1) | CHAR_BASE(1) | BG_256_COLOR | SCREEN_BASE(1) | BG_SIZE_0;

  // mosaic works: *((u16*)0x400004C) = (3 << 0) | (3 << 4);
  
  // alpha: doesn't work
  //*((u16*)0x4000050) = (0 << 0) | (1 << 8) | (3 << 6);
  //*((u16*)0x4000052) = (3 << 8) | (16);

  set_palette(tileset_pal_raw);
  set_tileset(2, tileset_img_raw);
  set_tileset(1, tileset_img_raw);

  {
    u16 i;
    for(i = 0; i < 1024; i+=1)
      ((u16*)MAP_BASE_ADR(0))[i] = i;

    for(i = 0; i < 1024; i+=1)
      ((u16*)MAP_BASE_ADR(1))[i] = (1024-i) | (1<<0xb)| (1<<0xa);
  }

  //FadeToPalette( PaletteBuffer, 60);

  bg_scroll scroll, scroll2;
  scroll.x = 0;
  scroll.y = 0;
  scroll2.x = 0;
  scroll2.y = 0;
  while (1)
    {
      u16 keys = KeysHeld();
      if (keys & KEY_UP)
        {
          scroll.y += 1;
          scroll2.y += 2;
        }
      else if (keys & KEY_DOWN)
        {
          scroll.y -= 1;
          scroll2.y -= 2;
        }
      
      if (keys & KEY_LEFT)
        {
          scroll.x += 1;
          scroll2.x += 2;
        }
      else if (keys & KEY_RIGHT)
        {
          scroll.x -= 1;
          scroll2.x -= 2;
        }

      BG_OFFSET[0] = scroll2;
      BG_OFFSET[1] = scroll;
          
      VBlankIntrWait();
    }
}


